baseURL = 'https://hellscaped.dev/'
languageCode = 'en-us'
title = "Hey, I'm Hellscaped"
theme = 'terminal'
pagination.pagerSize = 5
enableGitInfo = true

# Required for Chroma and the custom syntax highlighting.
[markup.highlight]
  noClasses = false

[params]
  copyrightStart = "2026"
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = true

  # center theme with default width
  centerTheme = true

  # if your resource directory contains an image called `cover.(jpg|png|webp)`,
  # then the file will be used as a cover automatically.
  # With this option you don't have to put the `cover` param in a front-matter.
  autoCover = true

  showLastUpdated = true


[languages]
  [languages.en]
    languageName = "English"
    title = "Hey, I'm Hellscaped"
    copyright = "Riley Thrailkill"
    [languages.en.params]
      subtitle = "I do things"
      owner = "Hellscaped"
      keywords = "home, blog, games"
      menuMore = "Show more"
      readMore = "Read more"
      readOtherPosts = "Read other posts"
      newerPosts = "Newer posts"
      olderPosts = "Older posts"
      missingContentMessage = "Page not found..."
      missingBackButtonLabel = "Back to home page"
      minuteReadingTime = "min read"
      words = "words"

      [languages.en.params.logo]
        logoText = "Hellscaped"
        logoHomeLink = "/"

      [languages.en.menu]
        [[languages.en.menu.main]]
          identifier = "blog"
          name = "Blog"
          url = "/posts"
        [[languages.en.menu.main]]
          identifier = "games"
          name = "Games"
          url = "/games"

[outputs]
home = ['html']
section = ['html']
taxonomy = ['html']
term = ['html']

[outputFormats.RSS]
mediaType = "application/rss+xml"
baseName = "rss"
